-- 1~4월 수입 데이터
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 1, id, 5300000 FROM categories WHERE type='income' AND main_category='월급' AND sub_category='남편월급';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 3, id, 6400000 FROM categories WHERE type='income' AND main_category='월급' AND sub_category='남편월급';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 4, id, 11300000 FROM categories WHERE type='income' AND main_category='월급' AND sub_category='남편월급';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 1, id, 3915391 FROM categories WHERE type='income' AND main_category='월급' AND sub_category='아내월급';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 2, id, 4158615 FROM categories WHERE type='income' AND main_category='월급' AND sub_category='아내월급';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 3, id, 3131925 FROM categories WHERE type='income' AND main_category='월급' AND sub_category='아내월급';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 4, id, 3012005 FROM categories WHERE type='income' AND main_category='월급' AND sub_category='아내월급';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 1, id, 6507 FROM categories WHERE type='income' AND main_category='금융소득' AND sub_category='예적금이자';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 2, id, 9858 FROM categories WHERE type='income' AND main_category='금융소득' AND sub_category='예적금이자';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 3, id, 5407 FROM categories WHERE type='income' AND main_category='금융소득' AND sub_category='예적금이자';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 4, id, 8369 FROM categories WHERE type='income' AND main_category='금융소득' AND sub_category='예적금이자';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 1, id, 4241666 FROM categories WHERE type='income' AND main_category='금융소득' AND sub_category='RS딜';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 2, id, 1541666 FROM categories WHERE type='income' AND main_category='금융소득' AND sub_category='RS딜';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 3, id, 1541666 FROM categories WHERE type='income' AND main_category='금융소득' AND sub_category='RS딜';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 4, id, 1541666 FROM categories WHERE type='income' AND main_category='금융소득' AND sub_category='RS딜';
INSERT INTO incomes (year, month, category_id, amount) SELECT 2026, 4, id, 195000 FROM categories WHERE type='income' AND main_category='기타' AND sub_category='중고판매';

-- 1~4월 저축 데이터
INSERT INTO savings (year, month, category_id, amount) SELECT 2026, 1, id, 20000 FROM categories WHERE type='saving' AND main_category='예적금' AND sub_category='주택청약저축';
INSERT INTO savings (year, month, category_id, amount) SELECT 2026, 2, id, 20000 FROM categories WHERE type='saving' AND main_category='예적금' AND sub_category='주택청약저축';
INSERT INTO savings (year, month, category_id, amount) SELECT 2026, 3, id, 20000 FROM categories WHERE type='saving' AND main_category='예적금' AND sub_category='주택청약저축';
INSERT INTO savings (year, month, category_id, amount) SELECT 2026, 4, id, 20000 FROM categories WHERE type='saving' AND main_category='예적금' AND sub_category='주택청약저축';

-- 1~4월 지출 데이터
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '관리비', 304610, '이월데이터', id FROM categories WHERE type='expense' AND main_category='주거' AND sub_category='관리비';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '관리비', 326880, '이월데이터', id FROM categories WHERE type='expense' AND main_category='주거' AND sub_category='관리비';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '관리비', 284170, '이월데이터', id FROM categories WHERE type='expense' AND main_category='주거' AND sub_category='관리비';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '관리비', 295080, '이월데이터', id FROM categories WHERE type='expense' AND main_category='주거' AND sub_category='관리비';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '대출이자', 450000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='주거' AND sub_category='대출이자';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '대출이자', 450000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='주거' AND sub_category='대출이자';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '대출이자', 850000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='주거' AND sub_category='대출이자';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '식자재', 381000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='식자재';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '식자재', 314090, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='식자재';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '식자재', 305856, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='식자재';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '식자재', 527505, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='식자재';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '외식', 331500, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='외식';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '외식', 341280, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='외식';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '외식', 63500, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='외식';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '외식', 614280, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='외식';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '카페류', 77300, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='카페류';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '카페류', 35500, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='카페류';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '카페류', 12800, '이월데이터', id FROM categories WHERE type='expense' AND main_category='식비' AND sub_category='카페류';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '생활소모품', 337110, '이월데이터', id FROM categories WHERE type='expense' AND main_category='생활용품' AND sub_category='생활소모품';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '생활소모품', 21310, '이월데이터', id FROM categories WHERE type='expense' AND main_category='생활용품' AND sub_category='생활소모품';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '생활소모품', 191781, '이월데이터', id FROM categories WHERE type='expense' AND main_category='생활용품' AND sub_category='생활소모품';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '생활소모품', 213988, '이월데이터', id FROM categories WHERE type='expense' AND main_category='생활용품' AND sub_category='생활소모품';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '가전/가구', 140139, '이월데이터', id FROM categories WHERE type='expense' AND main_category='생활용품' AND sub_category='가전/가구';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '의류/잡화', 119600, '이월데이터', id FROM categories WHERE type='expense' AND main_category='꾸밈비' AND sub_category='의류/잡화';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '의류/잡화', 96100, '이월데이터', id FROM categories WHERE type='expense' AND main_category='꾸밈비' AND sub_category='의류/잡화';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '의류/잡화', 232080, '이월데이터', id FROM categories WHERE type='expense' AND main_category='꾸밈비' AND sub_category='의류/잡화';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '의류/잡화', 44510, '이월데이터', id FROM categories WHERE type='expense' AND main_category='꾸밈비' AND sub_category='의류/잡화';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '미용/헤어', 26718, '이월데이터', id FROM categories WHERE type='expense' AND main_category='꾸밈비' AND sub_category='미용/헤어';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '병원/약국', 8300, '이월데이터', id FROM categories WHERE type='expense' AND main_category='건강' AND sub_category='병원/약국';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '병원/약국', 39100, '이월데이터', id FROM categories WHERE type='expense' AND main_category='건강' AND sub_category='병원/약국';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '스터디/수강', 270000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='스터디/수강';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '스터디/수강', 100000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='스터디/수강';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '운동', 413750, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='운동';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '운동', 53500, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='운동';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '운동', 101800, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='운동';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '운동', 176257, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='운동';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '도서', 19000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='도서';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '구독/레터', 32000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='구독/레터';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '구독/레터', 32582, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='구독/레터';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '구독/레터', 33004, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자기계발' AND sub_category='구독/레터';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '주유', 100000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='주유';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '주유', 50000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='주유';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '주유', 40000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='주유';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '대중교통', 11200, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='대중교통';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '대중교통', 1800, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='대중교통';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '보험/세금', 15100, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='보험/세금';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '보험/세금', 15100, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='보험/세금';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '보험/세금', 15100, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='보험/세금';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '보험/세금', 15100, '이월데이터', id FROM categories WHERE type='expense' AND main_category='자동차' AND sub_category='보험/세금';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '해외여행', 3065066, '이월데이터', id FROM categories WHERE type='expense' AND main_category='여행' AND sub_category='해외여행';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '공연/전시', 7000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='문화생활' AND sub_category='공연/전시';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '공연/전시', 33400, '이월데이터', id FROM categories WHERE type='expense' AND main_category='문화생활' AND sub_category='공연/전시';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '기타 여가비', 113000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='문화생활' AND sub_category='기타 여가비';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '기타 여가비', 22000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='문화생활' AND sub_category='기타 여가비';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '가족/친척', 692900, '이월데이터', id FROM categories WHERE type='expense' AND main_category='경조사' AND sub_category='가족/친척';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '가족/친척', 347400, '이월데이터', id FROM categories WHERE type='expense' AND main_category='경조사' AND sub_category='가족/친척';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '지인/동료', 37400, '이월데이터', id FROM categories WHERE type='expense' AND main_category='경조사' AND sub_category='지인/동료';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '지인/동료', 88000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='경조사' AND sub_category='지인/동료';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '남편용돈', 300000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='남편용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '남편용돈', 300000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='남편용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '남편용돈', 300000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='남편용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '남편용돈', 300000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='남편용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '아내용돈', 150000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='아내용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '아내용돈', 150000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='아내용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '아내용돈', 150000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='아내용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '아내용돈', 150000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='아내용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '부모님 용돈', 200000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='부모님 용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '부모님 용돈', 200000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='부모님 용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '부모님 용돈', 200000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='부모님 용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '부모님 용돈', 200000, '이월데이터', id FROM categories WHERE type='expense' AND main_category='용돈' AND sub_category='부모님 용돈';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '남편보험', 110520, '이월데이터', id FROM categories WHERE type='expense' AND main_category='보험' AND sub_category='남편보험';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '남편보험', 110520, '이월데이터', id FROM categories WHERE type='expense' AND main_category='보험' AND sub_category='남편보험';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '남편보험', 110520, '이월데이터', id FROM categories WHERE type='expense' AND main_category='보험' AND sub_category='남편보험';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '남편보험', 110520, '이월데이터', id FROM categories WHERE type='expense' AND main_category='보험' AND sub_category='남편보험';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '아내보험', 89115, '이월데이터', id FROM categories WHERE type='expense' AND main_category='보험' AND sub_category='아내보험';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '아내보험', 89115, '이월데이터', id FROM categories WHERE type='expense' AND main_category='보험' AND sub_category='아내보험';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '아내보험', 89115, '이월데이터', id FROM categories WHERE type='expense' AND main_category='보험' AND sub_category='아내보험';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '아내보험', 89115, '이월데이터', id FROM categories WHERE type='expense' AND main_category='보험' AND sub_category='아내보험';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '남편휴대폰', 19890, '이월데이터', id FROM categories WHERE type='expense' AND main_category='통신비' AND sub_category='남편휴대폰';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '남편휴대폰', 19890, '이월데이터', id FROM categories WHERE type='expense' AND main_category='통신비' AND sub_category='남편휴대폰';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '남편휴대폰', 19890, '이월데이터', id FROM categories WHERE type='expense' AND main_category='통신비' AND sub_category='남편휴대폰';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '남편휴대폰', 19890, '이월데이터', id FROM categories WHERE type='expense' AND main_category='통신비' AND sub_category='남편휴대폰';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 1, '2026-01-01', '아내휴대폰', 19910, '이월데이터', id FROM categories WHERE type='expense' AND main_category='통신비' AND sub_category='아내휴대폰';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 2, '2026-02-01', '아내휴대폰', 430, '이월데이터', id FROM categories WHERE type='expense' AND main_category='통신비' AND sub_category='아내휴대폰';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 3, '2026-03-01', '아내휴대폰', 110, '이월데이터', id FROM categories WHERE type='expense' AND main_category='통신비' AND sub_category='아내휴대폰';
INSERT INTO transactions (year, month, date, merchant, amount, card_type, category_id) SELECT 2026, 4, '2026-04-01', '아내휴대폰', 110, '이월데이터', id FROM categories WHERE type='expense' AND main_category='통신비' AND sub_category='아내휴대폰';-- 1~4월 자산 데이터
-- 부동산
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'fixed', '부동산', '아파트', 870000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'fixed', '부동산', '아파트', 870000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'fixed', '부동산', '아파트', 870000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'fixed', '부동산', '아파트', 870000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'fixed', '부동산', '전세 보증금', 425000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'fixed', '부동산', '전세 보증금', 425000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'fixed', '부동산', '전세 보증금', 425000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'fixed', '부동산', '전세 보증금', 425000000);
-- 노후/연금
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'fixed', '노후/연금', '남편개인연금', 21754545);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'fixed', '노후/연금', '남편개인연금', 21754545);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'fixed', '노후/연금', '남편개인연금', 21754545);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'fixed', '노후/연금', '남편개인연금', 23000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'fixed', '노후/연금', '아내개인연금', 26925679);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'fixed', '노후/연금', '아내개인연금', 27219311);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'fixed', '노후/연금', '아내개인연금', 26907780);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'fixed', '노후/연금', '아내개인연금', 29067385);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'fixed', '노후/연금', '아내퇴직연금', 6443040);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'fixed', '노후/연금', '아내퇴직연금', 6519805);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'fixed', '노후/연금', '아내퇴직연금', 6432787);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'fixed', '노후/연금', '아내퇴직연금', 6473905);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'fixed', '노후/연금', '남편관리통장', 20000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'fixed', '노후/연금', '남편관리통장', 20000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'fixed', '노후/연금', '남편관리통장', 20000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'fixed', '노후/연금', '남편관리통장', 20000000);
-- 저축/투자
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'liquid', '저축/투자', '예적금', 6240000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'liquid', '저축/투자', '예적금', 6260000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'liquid', '저축/투자', '예적금', 6280000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'liquid', '저축/투자', '예적금', 6300000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'liquid', '저축/투자', 'RS딜', 120000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'liquid', '저축/투자', 'RS딜', 120000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'liquid', '저축/투자', 'RS딜', 130000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'liquid', '저축/투자', 'RS딜', 130000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'liquid', '저축/투자', '키움주식', 6540041);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'liquid', '저축/투자', '키움주식', 6830712);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'liquid', '저축/투자', '키움주식', 6250000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'liquid', '저축/투자', '키움주식', 6473905);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'liquid', '저축/투자', '비상금통장', 8760866);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'liquid', '저축/투자', '비상금통장', 5615740);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'liquid', '저축/투자', '비상금통장', 5380358);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'liquid', '저축/투자', '비상금통장', 6985621);
-- 대출 (부채)
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'debt', '대출', '주택담보대출', -300000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'debt', '대출', '주택담보대출', -300000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'debt', '대출', '주택담보대출', -300000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'debt', '대출', '주택담보대출', -300000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'debt', '대출', '친정론/시댁론', -100000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'debt', '대출', '친정론/시댁론', -100000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'debt', '대출', '친정론/시댁론', -100000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'debt', '대출', '친정론/시댁론', -100000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 1, 'debt', '대출', '신용대출', -116000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 2, 'debt', '대출', '신용대출', -116000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 3, 'debt', '대출', '신용대출', -116000000);
INSERT INTO assets (year, month, asset_type, main_category, sub_category, amount) VALUES (2026, 4, 'debt', '대출', '신용대출', -116000000);